### ISSUE TITLE
Missing master sqlite database file. Please check your setup

### ISSUE THREAD

**Issue by yendrifernando** [prashants/webzash#46]
It occure after following the video - Installation, i have change the permisson of tmp to 777 and change AllowOverride All on /var/www/ in ubuntu.

**Comment by prashants** [comment]
Can you reinstall the app and try again from scratch. If it still doesn't work post a screenshot.

**Comment by yendrifernando** [comment]
Firstly, i extract webzash-v2.6.zip on /var/www/html/webzash. So, i found this :

Warning: _cake_core_ cache was unable to write 'cake_dev_en-us' to File cache in /var/www/html/webzash/lib/Cake/Cache/Cache.php on line 323

Warning: /var/www/html/webzash/app/tmp/cache/persistent/ is not writable in /var/www/html/webzash/lib/Cake/Cache/Engine/FileEngine.php on line 385

Fatal error: Uncaught exception 'CacheException' with message 'Cache engine _cake_core_ is not properly configured.' in /var/www/html/webzash/lib/Cake/Cache/Cache.php:181 Stack trace: #0 /var/www/html/webzash/lib/Cake/Cache/Cache.php(151): Cache::_buildEngine('_cake_core_') #1 /var/www/html/webzash/app/Config/core.php(374): Cache::config('_cake_core_', Array) #2 /var/www/html/webzash/lib/Cake/Core/Configure.php(72): include('/var/www/html/w...') #3 /var/www/html/webzash/lib/Cake/bootstrap.php(175): Configure::bootstrap(true) #4 /var/www/html/webzash/app/webroot/index.php(90): include('/var/www/html/w...') #5 {main} thrown in /var/www/html/webzash/lib/Cake/Cache/Cache.php on line 181

Secondly, i make the /tmp folder 777 permission : 
So, this error is appear :

'Missing master sqlite database file. Please check your setup.'

**Comment by prashants** [comment]
Does your PHP version have support for sqlite ?

Also check if the app/Plugin/Webzash/Database/webzash.sqlite file exists.

**Comment by yendrifernando** [comment]
I think my php was support to sqlite. I have installed PHP Version 5.5.9.
There is text like this on my php info :
SQLite 3.x driver for PDO 	Wez Furlong
SQLite3 	                                Scott MacVicar, Ilia Alshanetsky, Brad Dewar 

And webzash.sqlite is exist.

**Comment by prashants** [comment]
Can you use bitnami lamp stack for now. It seem there is some issue with your setup. Maybe disable SELinux ?

**Comment by yendrifernando** [comment]
so, as admin, where i can find the list of full access?

On 12/7/15, Prashant Shah <notifications@github.com> wrote:
> Can you use bitnami lamp stack for now. It seem there is some issue with
> your setup. Maybe disable SELinux ?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/prashants/webzash/issues/46#issuecomment-162419539


-- 


*@yendrifernando
**yendrifernando.wordpress.com*

**Comment by yendrifernando** [comment]
ok. it's done. After i have installed lamp stack from bitnami i can run webzash (development step) normally. Thank you.

but while i install webzash via webzash-v2.6.zip (i extract it), i have found this message error ;
------------------------
The request has been black-holed

Error: The requested address '/webzash/wzusers/login' was not found on this server.

**Comment by prashants** [comment]
https://github.com/prashants/webzash/wiki/Installation-Problems
